### ISSUE TITLE
Creating a group causes a crash

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [nlogozzo/NickvisionMoney#243]
To reproduce, simply try to create a new group. The group will be created, but Denaro crashes right after.

Version `2023.1.0-rc2`

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '3' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NickvisionMoney.Shared.Controllers.AccountViewController.GetUIGroupRowFromIndex(Int32 index) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 357
   at NickvisionMoney.GNOME.Views.AccountView.CreateGroupRow(Group group, Nullable`1 index) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 557
   at NickvisionMoney.Shared.Controllers.AccountViewController.AddGroupAsync(Group group) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 649
   at NickvisionMoney.GNOME.Views.AccountView.NewGroup(SimpleAction sender, EventArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 894
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by nlogozzo** [comment]
I believe this is fixed in the latest stable version...V2023.1.1

**Comment by nlogozzo** [comment]
Try that and let me know

**Comment by SoMuchForSubtlety** [comment]
I can confirm that it's fixed.

Will the flathub beta channel be behind the main channel regularly?

**Comment by fsobolev** [comment]
Beta and RC versions are considered unsafe to use with real data, so I think it's better to keep versions separated like it is now: only stable versions on stable branch and only unstable versions on beta branch. This way users will not be tempted to always use beta branch, it's not intended for real use, only for testing.

**Comment by nlogozzo** [comment]
You know I was thinking of keeping them separate, just beta for beta, and stable for stable but I can see how it's useful to keep beta up to date so I will do that when I get home :)

**Comment by nlogozzo** [comment]
I didn't see @fsobolev 's response...now I'm conflicts haha 

I see the benefits of both sides
But on second thought I think it's best to keep them separate 
You can install both of them and run stable with flatpak run org.nickvision.money//stable and for beta change it to beta
