### ISSUE TITLE
Denaro crashes when trying to create an account

### ISSUE THREAD

**Issue by eldelacajita** [nlogozzo/NickvisionMoney#305]
It happens while trying to create the first account.
The account file is created in the desired location, however.
When trying to add that existing account, it crashes again. 

I'm using the **Flatpak** version on **EndeavourOS** with **GNOME 43.2** on **Wayland**.

This is what I get when running it from the terminal: 
```
[user@computer ~]$ flatpak run org.nickvision.money
(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 16:02:02.234: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed
(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 16:02:02.234: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at NickvisionMoney.Shared.Models.Account.get_IsEncrypted() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Models/Account.cs:line 118
   at NickvisionMoney.Shared.Controllers.AccountViewController.get_AccountNeedsPassword() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 73
   at NickvisionMoney.Shared.Controllers.MainWindowController.AddAccountAsync(String path, Boolean showOpenedNotification, String password) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/MainWindowController.cs:line 200
   at NickvisionMoney.GNOME.Views.MainWindow.<>c__DisplayClass57_0.<<OnOpenAccount>b__0>d.MoveNext() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/MainWindow.cs:line 460
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by nlogozzo** [comment]
Was this a password protected account?

**Comment by eldelacajita** [comment]
I didn't get to a part of the process where I could set a password up. I hit "New account", select a location and file name, hit "Save", and after a couple of seconds the app crashes.

**Comment by fsobolev** [comment]
Where do you try to save a file? Flatpak has access to home directory, but nothing else.
Can you send a file that was created? (Since you didn't save any data in it, it doesn't contain any sensitive information)

**Comment by eldelacajita** [comment]
> Where do you try to save a file? Flatpak has access to home directory, but nothing else.

Ah, this is definitely related to the issue. I was trying to store it on a mounted NTFS partition to which I gave it access via de Applications settings, adding the folder to the filesystem permissions. If I try to save it to somewhere inside the home directory, it does work.

This is the file: [cuenta-triodos.zip](https://github.com/nlogozzo/NickvisionMoney/files/10726808/cuenta-triodos.zip)

**Comment by nlogozzo** [comment]
> > Where do you try to save a file? Flatpak has access to home directory, but nothing else.
> 
> Ah, this is definitely related to the issue. I was trying to store it on a mounted NTFS partition to which I gave it access via de Applications settings, adding the folder to the filesystem-related permissions. If I try to save it to somewhere inside the home directory, it does work.

The recommended action is to use the application `Flatseal` to allow Denaro access to the filesystem fully and it should fix the problem.
