### ISSUE TITLE
Making a Change to an existing transaction crashes the app

### ISSUE THREAD

**Issue by mepowerleo10** [nlogozzo/NickvisionMoney#350]
When I update an existing entry of a transaction, like the type of the transaction or the group the app crashes.

### Steps to reproduce
1. Create a new transaction and fill in the required fields
2. Save the transaction
3. Open an existing transaction, and change its group
4. Save the change

### Output
The app hangs and crashes

### Stack trace
```bash
(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 08:53:37.896: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 08:53:37.896: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
Registering new type NickvisionMoneyGNOMEControlsGroupRow with parent AdwActionRow
Registering new type NickvisionMoneyGNOMEControlsTransactionRow with parent AdwPreferencesGroup
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Image`1'.
   at SixLabors.ImageSharp.Image.ThrowObjectDisposedException(Type type)
   at SixLabors.ImageSharp.Image.EnsureNotDisposed()
   at SixLabors.ImageSharp.Image.SaveAsync(Stream stream, IImageEncoder encoder, CancellationToken cancellationToken)
   at NickvisionMoney.Shared.Models.Account.UpdateTransactionAsync(Transaction transaction) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Models/Account.cs:line 847
   at NickvisionMoney.Shared.Controllers.AccountViewController.UpdateTransactionAsync(Transaction transaction) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 647
   at NickvisionMoney.GNOME.Views.AccountView.<>c__DisplayClass92_0.<<EditTransaction>b__1>d.MoveNext() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 1087
--- End of stack trace from previous location ---
   at NickvisionMoney.GNOME.Views.AccountView.<>c__DisplayClass92_0.<<EditTransaction>b__0>d.MoveNext() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 1087
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
**Denaro Version**: 2023.2.2
**OS**: Fedora Linux 37 (Workstation Edition) x86_64
**Kernel**: 6.1.14-200.fc37.x86_64

**Comment by nlogozzo** [comment]
When you first created this transaction, did you add a receipt?

**Comment by mepowerleo10** [comment]
> When you first created this transaction, did you add a receipt?

Yes added a picture of the receipt

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.3.0-beta1
