### ISSUE TITLE
Adding Transaction after importing .CSV with unordered ID cause the application crashed

### ISSUE THREAD

**Issue by Krindog7337** [nlogozzo/NickvisionMoney#405]
When user creating new account and importing transactions from .CSV file which contains some missing ID, after importing all the transactions then adding new transactions the application will crash

>CSV file example (this file doesn't have the ID 2 and ID 3 transactions)
```
ID;Date (en_US Format);Description;Type;RepeatInterval;RepeatFrom (-1=None,0=Original,Other=Id Of Source);RepeatEndDate (en_US Format);Amount (en_US Format);RGBA;Group(Id Starts At 1);GroupName;GroupDescription
1;3/29/2023;a;0;0;-1;;1000;rgb(53,132,228);-1;;
4;3/29/2023;a;0;0;-1;;1000;rgb(53,132,228);-1;;
5;3/29/2023;asdf;0;0;-1;;12313;rgb(53,132,228);-1;;
``` 

However, if users _reopened_ the app after importing, the app will just fine

>error log
```
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: transactions.id'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at NickvisionMoney.Shared.Models.Account.AddTransactionAsync(Transaction transaction) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Models/Account.cs:line 800
   at NickvisionMoney.Shared.Controllers.AccountViewController.AddTransactionAsync(Transaction transaction) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 613
   at NickvisionMoney.GNOME.Views.AccountView.<>c__DisplayClass90_0.<<NewTransaction>b__1>d.MoveNext() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 935
--- End of stack trace from previous location ---
   at NickvisionMoney.GNOME.Views.AccountView.<>c__DisplayClass90_0.<<NewTransaction>b__0>d.MoveNext() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 935
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.4.0-beta1
