### ISSUE TITLE
Crash on opening file with Nautilus

### ISSUE THREAD

**Issue by DuckDuckWhale** [nlogozzo/NickvisionMoney#412]
```
$ flatpak run --file-forwarding org.nickvision.money @@ 'file.nmoney' @@
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.IntPtr' to type 'Gio.File[]'.
   at GObject.Value.Extract[T]()
   at Gio.Application.OpenSignalArgs.get_Files()
   at NickvisionMoney.GNOME.Program.OnOpen(Application sender, OpenSignalArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Program.cs:line 122
   at GObject.Signal`2.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)
```

**Comment by fsobolev** [comment]
Fixed in https://github.com/nlogozzo/NickvisionMoney/commit/42cd9f9b58c2c54c35696130ae50b213640aed17
Works as expected in latest beta
